library(plotrix)

tiff('figure_1.tiff', width = 4, height = 4, units = "in", res = 300)
old.par <- par()
par(mai = c(0,0,0,0), pty = "s")
plot(0, type = "n", bty = "n", xlim = c(-0.3, 4.3), ylim = c(-0.3, 4.3), 
     xaxt = "n", yaxt = "n", xlab = "", ylab = "")
abline(h = c(0, 1, 2, 3, 4), col = "black", lwd = 2, lty = 1)
abline(v = c(0, 1, 2, 3, 4), col = "black", lwd = 2, lty = 1)
draw.circle(x = 0, y = 0, radius = 0.25, border = "black", col = "white")
draw.circle(x = 0, y = 1, radius = 0.25, border = "black", col = "white")
draw.circle(x = 0, y = 2, radius = 0.25, border = "black", col = "white")
draw.circle(x = 0, y = 3, radius = 0.25, border = "black", col = "white")
draw.circle(x = 0, y = 4, radius = 0.25, border = "black", col = "white")
draw.circle(x = 1, y = 0, radius = 0.25, border = "black", col = "white")
draw.circle(x = 1, y = 1, radius = 0.25, border = "black", col = "white")
draw.circle(x = 1, y = 2, radius = 0.25, border = "black", col = "gray")
draw.circle(x = 1, y = 3, radius = 0.25, border = "black", col = "white")
draw.circle(x = 1, y = 4, radius = 0.25, border = "black", col = "white")
draw.circle(x = 2, y = 0, radius = 0.25, border = "black", col = "white")
draw.circle(x = 2, y = 1, radius = 0.25, border = "black", col = "gray")
draw.circle(x = 2, y = 2, radius = 0.25, border = "black", col = "black")
draw.circle(x = 2, y = 3, radius = 0.25, border = "black", col = "gray")
draw.circle(x = 2, y = 4, radius = 0.25, border = "black", col = "white")
draw.circle(x = 3, y = 0, radius = 0.25, border = "black", col = "white")
draw.circle(x = 3, y = 1, radius = 0.25, border = "black", col = "white")
draw.circle(x = 3, y = 2, radius = 0.25, border = "black", col = "gray")
draw.circle(x = 3, y = 3, radius = 0.25, border = "black", col = "white")
draw.circle(x = 3, y = 4, radius = 0.25, border = "black", col = "white")
draw.circle(x = 4, y = 0, radius = 0.25, border = "black", col = "white")
draw.circle(x = 4, y = 1, radius = 0.25, border = "black", col = "white")
draw.circle(x = 4, y = 2, radius = 0.25, border = "black", col = "white")
draw.circle(x = 4, y = 3, radius = 0.25, border = "black", col = "white")
draw.circle(x = 4, y = 4, radius = 0.25, border = "black", col = "white")
par <- old.par
dev.off()